#!/usr/bin/env python3
"""
AppFactoryKit app generator.

Turns one niche from niches.json into a buildable iOS app project wired to
AppFactoryKit. Output is an XcodeGen project: run `xcodegen generate` in the
output folder, then open the .xcodeproj.

Usage:
    python3 generate.py <niche-id> [options]
    python3 generate.py --list
    python3 generate.py ai-headshot --bundle-prefix com.zubeid --out ~/AppFactoryPortfolio

The generated app runs immediately in the simulator on a MockPurchaseProvider
(real paywall UI, fake purchases). Drop in a RevenueCat key to go live.
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
KIT_ROOT = os.path.abspath(os.path.join(ROOT, "..", ".."))   # ~/AppFactoryKit
CATALOG = os.path.join(ROOT, "niches.json")

# Category → (SwiftUI color name, SF Symbol hero, second onboarding symbol)
CATEGORY_STYLE = {
    "AI Image":      ("purple", "wand.and.stars", "photo.on.rectangle.angled"),
    "AI Vision":     ("green",  "viewfinder.circle", "sparkle.magnifyingglass"),
    "AI Text":       ("blue",   "text.bubble", "sparkles"),
    "AI Audio":      ("pink",   "waveform", "mic.fill"),
    "Scanning":      ("blue",   "doc.viewfinder", "doc.text.magnifyingglass"),
    "QR":            ("teal",   "qrcode.viewfinder", "qrcode"),
    "Finance":       ("green",  "dollarsign.circle", "chart.line.uptrend.xyaxis"),
    "Health":        ("red",    "heart.fill", "figure.run"),
    "Wellness":      ("mint",   "leaf.fill", "moon.stars.fill"),
    "Productivity":  ("indigo", "checkmark.circle.fill", "bolt.fill"),
    "Lifestyle":     ("orange", "sparkles", "list.bullet"),
    "Media":         ("purple", "play.rectangle.fill", "scissors"),
    "Music":         ("pink",   "music.note", "metronome"),
    "Tools":         ("cyan",   "ruler.fill", "gauge"),
    "Customization": ("indigo", "paintbrush.fill", "apps.iphone"),
    "Privacy":       ("gray",   "lock.fill", "eye.slash.fill"),
    "Faith":         ("orange", "book.fill", "hands.sparkles.fill"),
    "Auto":          ("blue",   "car.fill", "wrench.and.screwdriver.fill"),
}
DEFAULT_STYLE = ("blue", "sparkles", "star.fill")

# Categories whose apps use the camera / photo library / microphone.
CAMERA_CATS = {"AI Image", "AI Vision", "Scanning", "QR", "Media", "Health"}
PHOTO_CATS = {"AI Image", "AI Vision", "Scanning", "Media", "Customization", "Health"}
MIC_CATS = {"AI Audio", "Music", "Media"}


def load_niche(niche_id):
    catalog = json.load(open(CATALOG))
    for n in catalog["niches"]:
        if n["id"] == niche_id:
            return n
    sys.exit(f"error: niche '{niche_id}' not found. Run --list to see all ids.")


def pascal(name):
    cleaned = re.sub(r"[^0-9a-zA-Z]+", " ", name)
    return "".join(w[:1].upper() + w[1:] for w in cleaned.split())


def benefits_from_hook(hook):
    icons = ["infinity", "bolt.fill", "nosign", "square.and.arrow.up",
             "star.fill", "lock.open.fill", "sparkles", "checkmark.seal.fill"]
    parts = [p.strip() for p in re.split(r"[,;]", hook) if p.strip()]
    out = []
    for i, p in enumerate(parts):
        title = p[:1].upper() + p[1:]
        out.append((icons[i % len(icons)], title))
    return out


def swift_str(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_app_swift(n, app_name, color, hero, hero2):
    bullets = benefits_from_hook(n["paywallHook"])
    benefit_lines = ",\n".join(
        f'                    .init(systemImage: "{ic}", title: "{swift_str(t)}")'
        for ic, t in bullets
    )
    return f'''import SwiftUI
import AppFactoryKit
import AppFactoryKitRevenueCat

// ─────────────────────────────────────────────────────────────────────────
// {app_name} — generated by AppFactoryKit appgen from niche "{n["id"]}".
// Per-app surface = this config + ContentView's feature. Everything that earns
// (onboarding, paywall, subscriptions, funnel) is inherited from the kit.
// ─────────────────────────────────────────────────────────────────────────

// Paste your RevenueCat public SDK key here to go live. Until then the app runs
// on a mock provider so you can preview the real paywall in the simulator.
private let revenueCatKey = "appl_REPLACE_ME"

@MainActor
enum {app_name}Factory {{
    static func make() -> AppFactory {{
        let provider: PurchaseProvider = revenueCatKey == "appl_REPLACE_ME"
            ? MockPurchaseProvider()
            : RevenueCatPurchaseProvider(apiKey: revenueCatKey, entitlementID: "premium")

        let config = AppFactoryConfiguration(
            appName: "{swift_str(app_name)}",
            purchaseProvider: provider,
            onboarding: OnboardingConfiguration(
                slides: [
                    .init(systemImage: "{hero}",
                          title: "{swift_str(app_name)}",
                          message: "{swift_str(n["utility"])}."),
                    .init(systemImage: "{hero2}",
                          title: "Go Pro",
                          message: "{swift_str(n["paywallHook"])}.")
                ],
                presentsPaywallOnFinish: true,
                accent: .{color}
            ),
            paywall: PaywallConfiguration(
                headline: "Unlock {swift_str(app_name)} Pro",
                subheadline: "{swift_str(n["paywallHook"])}.",
                benefits: [
{benefit_lines}
                ],
                productIDs: ["{n["id"]}_yearly", "{n["id"]}_weekly"],
                highlightedProductID: "{n["id"]}_yearly",
                ctaTitle: "Continue",
                dismissButtonDelay: 4,
                isDismissable: true,
                termsURL: URL(string: "https://YOURDOMAIN.com/terms"),
                privacyURL: URL(string: "https://YOURDOMAIN.com/privacy"),
                style: PaywallStyle(accent: .{color}, heroSystemImage: "{hero}")
            )
        )
        return AppFactory(config)
    }}
}}

@main
struct {app_name}App: App {{
    @StateObject private var factory = {app_name}Factory.make()

    var body: some Scene {{
        WindowGroup {{
            ContentView()
                .appFactoryRoot(factory)
                .tint(.{color})
        }}
    }}
}}
'''


def render_content_swift(n, app_name, color, hero):
    return f'''import SwiftUI
import AppFactoryKit

// The ONLY genuinely app-specific code — your actual utility. Replace the stub
// below with the real feature. Gate premium actions with `requirePremium`.
struct ContentView: View {{
    @EnvironmentObject private var factory: AppFactory

    var body: some View {{
        NavigationStack {{
            VStack(spacing: 24) {{
                Spacer()
                Image(systemName: "{hero}")
                    .font(.system(size: 96))
                    .foregroundStyle(.{color})
                Text("{swift_str(n["utility"])}")
                    .font(.headline)
                    .multilineTextAlignment(.center)
                    .foregroundStyle(.secondary)
                    .padding(.horizontal, 32)

                // Free action — always available.
                Button("Try it") {{
                    // TODO: implement the core free feature
                }}
                .buttonStyle(.borderedProminent)

                // Premium action — runs if subscribed, else opens the paywall.
                // Tagged so the funnel shows this feature's upgrade rate.
                Button("Pro feature") {{
                    factory.requirePremium(feature: "pro_feature") {{
                        // TODO: implement the gated premium feature
                    }}
                }}
                .buttonStyle(.bordered)

                if !factory.subscriptions.isSubscribed {{
                    Button("Upgrade to Pro") {{
                        factory.presentPaywall(placement: "home_upsell")
                    }}
                    .font(.footnote)
                }}
                Spacer()
            }}
            .navigationTitle("{swift_str(app_name)}")
        }}
    }}
}}
'''


def render_project_yml(n, app_name, bundle_id):
    cat = n["category"]
    info_props = [
        f'        CFBundleDisplayName: "{app_name}"',
        "        UILaunchScreen: {}",
        '        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]',
    ]
    if cat in CAMERA_CATS:
        info_props.append(f'        NSCameraUsageDescription: "{app_name} uses the camera to capture and process your content."')
    if cat in PHOTO_CATS:
        info_props.append(f'        NSPhotoLibraryUsageDescription: "{app_name} needs access to your photos to import and process images."')
        info_props.append(f'        NSPhotoLibraryAddUsageDescription: "{app_name} saves your results to your photo library."')
    if cat in MIC_CATS:
        info_props.append(f'        NSMicrophoneUsageDescription: "{app_name} uses the microphone to record and process audio."')
    info_block = "\n".join(info_props)
    return f'''# Generated by AppFactoryKit appgen. Run: xcodegen generate
name: {app_name}
options:
  bundleIdPrefix: {bundle_id.rsplit(".", 1)[0]}
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

packages:
  AppFactoryKit:
    path: {KIT_ROOT}

targets:
  {app_name}:
    type: application
    platform: iOS
    sources:
      - Sources
    dependencies:
      - package: AppFactoryKit
        product: AppFactoryKit
      - package: AppFactoryKit
        product: AppFactoryKitRevenueCat
    info:
      path: Sources/Info.plist
      properties:
{info_block}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: {bundle_id}
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: NO
        CODE_SIGN_STYLE: Automatic
'''


def render_readme(n, app_name, bundle_id):
    return f'''# {app_name}

Generated from niche `{n["id"]}` ({n["category"]}, tier {n["tier"]}, score {n["score"]}).

**Utility:** {n["utility"]}
**Primary ASO keyword:** `{n["primaryKeyword"]}`
**Also target:** {", ".join("`%s`" % k for k in n["asoKeywords"])}
**Paywall hook:** {n["paywallHook"]}

> {n["notes"]}

## Build it

```bash
brew install xcodegen        # once
cd {app_name}
xcodegen generate
open {app_name}.xcodeproj
```

The app runs immediately on a MockPurchaseProvider (real paywall UI, fake
purchases). To go live:

1. Replace `revenueCatKey` in `Sources/App.swift` with your RevenueCat key.
2. In App Store Connect create products `{n["id"]}_yearly` and `{n["id"]}_weekly`,
   map them into a RevenueCat offering, entitlement id `premium`.
3. Build the real feature in `Sources/ContentView.swift`.
4. **Guideline 4.3:** make the function, UI, screenshots and keywords genuinely
   distinct from any sibling app. Re-niche, never reskin.

Bundle id: `{bundle_id}`
'''


def main():
    ap = argparse.ArgumentParser(description="Generate an iOS app from an AppFactoryKit niche.")
    ap.add_argument("niche_id", nargs="?", help="niche id from niches.json")
    ap.add_argument("--list", action="store_true", help="list all niche ids")
    ap.add_argument("--bundle-prefix", default="com.example", help="reverse-DNS bundle prefix")
    ap.add_argument("--out", default=os.path.expanduser("~/AppFactoryPortfolio"),
                    help="output directory (default ~/AppFactoryPortfolio)")
    ap.add_argument("--force", action="store_true", help="overwrite if the app folder exists")
    args = ap.parse_args()

    if args.list or not args.niche_id:
        catalog = json.load(open(CATALOG))
        for x in sorted(catalog["niches"], key=lambda z: -z["score"]):
            print(f"{x['score']:>3} {x['tier']}  {x['id']:<22} {x['name']}")
        return

    n = load_niche(args.niche_id)
    app_name = pascal(n["name"])
    color, hero, hero2 = CATEGORY_STYLE.get(n["category"], DEFAULT_STYLE)
    bundle_id = f"{args.bundle_prefix}.{n['id'].replace('-', '')}"

    app_dir = os.path.join(os.path.expanduser(args.out), app_name)
    src_dir = os.path.join(app_dir, "Sources")
    if os.path.exists(app_dir) and not args.force:
        sys.exit(f"error: {app_dir} already exists (use --force to overwrite)")
    os.makedirs(src_dir, exist_ok=True)

    files = {
        os.path.join(app_dir, "project.yml"): render_project_yml(n, app_name, bundle_id),
        os.path.join(src_dir, "App.swift"): render_app_swift(n, app_name, color, hero, hero2),
        os.path.join(src_dir, "ContentView.swift"): render_content_swift(n, app_name, color, hero),
        os.path.join(app_dir, "README.md"): render_readme(n, app_name, bundle_id),
        os.path.join(app_dir, ".gitignore"): "*.xcodeproj/\n.build/\nDerivedData/\n.DS_Store\n",
    }
    for path, content in files.items():
        with open(path, "w") as f:
            f.write(content)

    print(f"✅ Generated {app_name}  ({n['tier']}-tier, score {n['score']})")
    print(f"   {app_dir}")
    print(f"   Next: cd '{app_dir}' && xcodegen generate && open {app_name}.xcodeproj")


if __name__ == "__main__":
    main()
